# Write your MySQL query statement 

SELECT Visits.CUSTOMER_ID AS customer_id   , COUNT(*) AS count_no_trans  FROM VISITS 
LEFT JOIN TRANSACTIONS  ON VISITS.VISIT_ID = TRANSACTIONS.VISIT_ID 
WHERE TRANSACTIONS.VISIT_ID IS NULL 
GROUP BY Visits.CUSTOMER_ID 
ORDER BY Visits.CUSTOMER_ID; 
